### ISSUE TITLE
Interest in Makie support?

### ISSUE THREAD

**Issue by sc-dyer** [JuliaGeochronology/Isoplot.jl#5]
I've [hacked together](https://github.com/sc-dyer/Isoplot.jl/tree/makie) some limited support for Makie plotting and was wondering if there was any interest in incorporating this into the official package. I am not sure what the best approach would be to incorporate but making it work cohesively would probably require some refactoring. The "easiest" way I can imagine doing this is to move the functions not related to plotting to another package called "IsoplotCore.jl" or something like that and implementing the plotting functions in Isoplot.jl and a new package called "IsoplotMakie.jl" or something like that.

This might be more work than its worth but I figure some folks might prefer to use Makie over Plots.

**Comment by brenhinkeller** [comment]
Oh great! I would love to have this package support Makie too..

I think probably the best way to do it may be to use the new [package extensions](https://pkgdocs.julialang.org/v1/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)) system for both the Plots.jl plotting and the Makie plotting. This would mean we can do it all in this repo, but adding new `IsoplotPlotsExt.jl` and `IsoplotMakieExt.jl` files where the respective plotting code can live..

**Comment by brenhinkeller** [comment]
I recently got that system to work for one of my other packages -- https://github.com/brenhinkeller/StatGeochem.jl/blob/main/ext/StatGeochemPlotsExt.jl

The main trick IIRC was basically just that you can't define entirely new functions in the extension module, just add new methods to existing ones -- but that should be fine given that we'll just be wanting to add new methods to functions imported either from the respective plotting packages, or the main Isoplot.jl module

**Comment by sc-dyer** [comment]
Oh that seems relatively straightforward, I can look into implementing this locally when I have a spare moment and put in a pull request if I can get it to work.

**Comment by brenhinkeller** [comment]
That would be great!

**Comment by sc-dyer** [comment]
Submitted a [pull request ](https://github.com/JuliaGeochronology/Isoplot.jl/pull/6)

**Comment by brenhinkeller** [comment]
Closed by #6 🎉
