### ISSUE TITLE
Shift between MSWD calculated with Isoplot.jl and IsoplotR

### ISSUE THREAD

**Issue by Iddingsite** [JuliaGeochronology/Isoplot.jl#8]
Hi, 

I've observed a difference that I don't think is negligeable between MSWD calculated for wmean from Isoplot.jl and IsoplotR. I looked at the code here and have no issue with the way it is implemented in this package but I would like to understand what could be the reason for that. 

Here is a MWE if I take the data from the Readme and I just remove the 2 last analyses:

```
using Isoplot

# Example U-Pb dataset (MacLennan et al. 2020)
#       207/235  1σ abs   206/238     1σ abs     correlation
data = [1.1009 0.00093576 0.123906 0.00002849838 0.319
        1.1003 0.00077021 0.123901 0.00003531178 0.415
        1.0995 0.00049477 0.123829 0.00002538494 0.434
        1.0992 0.00060456 0.123813 0.00003652483 0.616
        1.1006 0.00071539 0.123813 0.00002228634 0.321
        1.0998 0.00076986 0.123802 0.00002537941 0.418
        1.0992 0.00065952 0.123764 0.00003589156 0.509
        1.0981 0.00109810 0.123727 0.00003959264 0.232
        1.0973 0.00052670 0.123612 0.00002966688 0.470
        1.0985 0.00087880 0.123588 0.00002842524 0.341]

# Turn into UPbAnalysis objects
analyses = UPbAnalysis.(eachcol(data)...,)

# Screen for discordance
ages = age68.(analyses)

wmean(ages; corrected=true)
```
This gives: `(752.26 ± 0.2, 1.963475224992393)` so MSWD of 1.96.
Now, if I do the same thing in IsoplotR I obtain this graph:

![Capture d’écran 2024-06-11 à 09 49 19](https://github.com/JuliaGeochronology/Isoplot.jl/assets/50744020/8d8cdace-b179-44bd-bc97-7128e3886a30)

So an MSWD of 13. This case is of course a bit extreme, but it is just to highlight the difference. I don't know how to use R so this is the output of the GUI, but I made sure to have the options that reflect what we have in Isoplot.jl. On more normally distributed data, the shift will be smaller but Isoplot.jl seems to always have a smaller MSWD. The wmean itself seems to be the same (and I've not activated the external uncertainty propagation in isoplotR, hence the smaller uncertainty).

I tried to look at the R code but I could not figure out what would cause that (and it is quite obscure to me as I don't know the language). Do you have any idea? 
Most of the time, this is not something really problematic as the MSWD is just an indicator, but for my case, I am calculating the long-term variance of my secondary std, and this is based on minimazing the value of MSWD to 1 so this would impact the uncertainty I obtain at the end.

**Comment by brenhinkeller** [comment]
Ah, at first glance it looks like this is probably because `age68` returns uncertainties including decay constant uncertainty, while `wmean` is expecting internal uncertainties only.

How to most elegantly prevent this sort of issue raises some interesting design problems — possibly either making a new custom type to store and report something like +/- x +/- y +/- z uncertainties, or else using Measurements.jl’s internal (though not particularly documented, IIRC) covariance tracking system

**Comment by Iddingsite** [comment]
Hi, this is indeed the case. Here, if I use only the raw data to compute a wmean, I obtain the same result than IsoplotR:

```
using Isoplot
using Measurements

# Example U-Pb dataset (MacLennan et al. 2020)
#       207/235  1σ abs   206/238     1σ abs     correlation
data = [1.1009 0.00093576 0.123906 0.00002849838 0.319
        1.1003 0.00077021 0.123901 0.00003531178 0.415
        1.0995 0.00049477 0.123829 0.00002538494 0.434
        1.0992 0.00060456 0.123813 0.00003652483 0.616
        1.1006 0.00071539 0.123813 0.00002228634 0.321
        1.0998 0.00076986 0.123802 0.00002537941 0.418
        1.0992 0.00065952 0.123764 0.00003589156 0.509
        1.0981 0.00109810 0.123727 0.00003959264 0.232
        1.0973 0.00052670 0.123612 0.00002966688 0.470
        1.0985 0.00087880 0.123588 0.00002842524 0.341]

# Turn into UPbAnalysis objects
analyses = UPbAnalysis.(eachcol(data)...,)

# calculate age68 and propagating systematic uncertainty on decay constant
ages = age68.(analyses)

wm_age68, MSWD_age68 = wmean(ages; corrected=true)

# calcule back the isotopic ratio to propagate systematic uncertainty on decay constant for the wmean
wm_age68 = exp(Isoplot.val(λ238U) * wm_age68) - 1
wm_age68_err = log(1 + wm_age68)/λ238U

wm, MSWD = wmean(data[:,3] .±  data[:,4]; corrected=true)

wm_age = log(1 + wm)/λ238U

@show wm_age68_err, MSWD_age68
@show wm_age, MSWD
```
Which output
```
(wm_age68_err, MSWD_age68) = (752.26 ± 0.45, 1.963475224992393)
(wm_age, MSWD) = (752.27 ± 0.45, 13.15782987942366)
```

I think this is an important issue.

In terms of design, a hotfix maybe a bit more dirty but without changing the internal structure of the code too much would be to convert back to the corresponding isotopic ratio of the age (without propagating the decay constant uncertainty) inside wmean to compute the wm and MSWD and to calculate back an age (propagating or not the decay cst with a Boolean maybe, because anyway other things should be propagated for a wm, a.k.a. long excess variance, ratio uncertainty of the primary reference material used for normalisation... If we follow Hostwood et al., 2016 recommandations) when an age is giving as input. That would preserve the good value of MSWD. That would require to have a new type for the ages that carries the corresponding lambda value and to apply multiple dispatch but it is maybe easier.

**Comment by brenhinkeller** [comment]
#9 should work for now and turns out to be nicely extensible, though still some design questions for later. `age68` is also maybe still a bit inelegant (and undocumented)
